trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'BicepDeploymentConnection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az bicep install'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'BicepDeploymentConnection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group validate 
        --resource-group rg-bicep-devops
        --template-file infra/main.bicep
        --parameters infra/main.parameters.json
