name: "Create Resource Group on Azure"

on: [ workflow_dispatch ]

env:
  BICEP_TEMPLATE_FILE: "./infra/deploy/main.bicep"

jobs:
  create-resource-group:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Resource Group
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          region: ${{ vars.AZURE_REGION }}
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
          template: ${{ env.BICEP_TEMPLATE_FILE }}
          parameters: location=${{ vars.AZURE_REGION }} resourceGroupName=${{ vars.AZURE_RESOURCE_GROUP_NAME }}
