name: Deploy Azure Infrastructure with Bicep

on: [ workflow_dispatch ]

env:
  AZURE_REGION: ${{ vars.AZURE_REGION }}
  AZURE_RESOURCE_GROUP_NAME: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
  BICEP_TEMPLATE_FILE: ./infra/deploy/main.bicep
  BICEP_PARAMETERS_FILE: ./infra/deploy/main.parameters.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infrastructure Code
        uses: actions/checkout@v3

      - name: Setup Bicep
        run: az bicep build --file infra/deploy/main.bicep

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Infrastructure Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template to Azure
        uses: azure/arm-deploy@v1
        with:
          failOnStdErr: false
          scope: subscription
          deploymentName: ${{ github.run_number }}
          region: ${{ env.AZURE_REGION }}
          template: ${{ env.BICEP_TEMPLATE_FILE }}
          parameters: ${{ env.BICEP_PARAMETERS_FILE }}
