name: "Lint/Validate/Deploy Azure IaC with Bicep v1"

concurrency: lint-validate-deploy

on: [ workflow_dispatch ]

env:
  AZURE_REGION: ${{ vars.AZURE_REGION }}
  BICEP_TEMPLATE_FILE: "./infra/deploy/main.bicep"
  BICEP_PARAMETERS_FILE: "./infra/deploy/main.parameters.json"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infrastructure Code
        uses: actions/checkout@v3

      - name: Lint Bicep code
        run: "az bicep build --file ${{ env.BICEP_TEMPLATE_FILE }}"

  validate:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Infrastructure Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Bicep Template
        uses: azure/arm-deploy@v2
        with:
          failOnStdErr: false
          scope: subscription
          region: ${{ env.AZURE_REGION }}
          template: ${{ env.BICEP_TEMPLATE_FILE }}
          parameters: ${{ env.BICEP_PARAMETERS_FILE }}
          deploymentName: ${{ github.run_number }}
          deploymentMode: Validate

  deploy:
    runs-on: ubuntu-latest
    needs: [ lint, validate ]
    steps:
      - name: Checkout Infrastructure Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template to Azure
        uses: azure/arm-deploy@v2
        with:
          failOnStdErr: false
          scope: subscription
          deploymentName: ${{ github.run_number }}
          region: ${{ env.AZURE_REGION }}
          template: ${{ env.BICEP_TEMPLATE_FILE }}
          parameters: ${{ env.BICEP_PARAMETERS_FILE }}
