name: Deploy Bicep file

on: [ workflow_dispatch ]

env:
  AZURE_REGION: ${{ vars.AZURE_REGION }}
  AZURE_RESOURCE_GROUP_NAME: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
  BICEP_TEMPLATE_FILE: ./infra/deploy/main.bicep
  BICEP_PARAMETERS_FILE: ./infra/deploy/main.parameters.json

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@main

      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          scope: 'resourcegroup'
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
          region: ${{ env.AZURE_REGION }}
          template: ${{ env.BICEP_TEMPLATE_FILE }}
          parameters: ${{ env.BICEP_PARAMETERS_FILE }}
          deploymentName: ${{ github.run_number }}
          failOnStdErr: false
